### ISSUE TITLE
Training EDSR (lambda=0.5)

### ISSUE THREAD

**Issue by krysma** [johnnysclai/SR_LRFR#1]
Hi,
The results of EDSR (lambda=0.5) model are very nice. Can you please provide more details about the training? (For example: Training datasets used in comparison with original EDSR paper; Influence of face alignments on EDSR results; ...)
Thanks.

**Comment by johnnysclai** [comment]
@krysma Sorry for late reply, I am preparing it and it will be released in few days.

**Comment by krysma** [comment]
@johnnysclai Thanks for response, and I am looking forward to see the solution.
