### ISSUE TITLE
identification部分的代码和数据集

### ISSUE THREAD

**Issue by ohtiger** [johnnysclai/SR_LRFR#4]
你好，能把identification部分的代码和数据集公开一下吗？我最近学习人脸识别相关的知识，想学习一下这部分的代码怎么写。

**Comment by johnnysclai** [comment]
We follows the protocol used in the paper "Simultaneous hallucination and recognition of low-resolution faces based on singular value decomposition". You can find the settings in the experiment section of that paper.
